#ifndef CONF_DRIVERS_H_
#define CONF_DRIVERS_H_

// USART
#define CONF_USART_POINTER 	(&AVR32_USART0)
#define CONF_USART_BAUDRATE	9600
#define CONF_USART_CHARLENGTH	8
#define CONF_USART_PARITYPE	USART_NO_PARITY
#define CONF_USART_STOPBITS	USART_2_STOPBITS
#define CONF_USART_CHANNELMODE USART_NORMAL_CHMODE

#endif /* CONF_DRIVERS_H_ */