#ifndef CONF_CLOCK_H_INCLUDED
#define CONF_CLOCK_H_INCLUDED

//#define CONFIG_SYSCLK_INIT_CPUMASK  (1 << SYSCLK_SYSTIMER)
#define CONFIG_SYSCLK_INIT_PBAMASK  (1 << SYSCLK_USART0)|(1 << SYSCLK_PWMA)
//#define CONFIG_SYSCLK_INIT_PBBMASK  (1 << SYSCLK_HMATRIX)
//#define CONFIG_SYSCLK_INIT_HSBMASK  (1 << SYSCLK_MDMA_HSB)

//#define CONFIG_SYSCLK_SOURCE          SYSCLK_SRC_RCSYS
//#define CONFIG_SYSCLK_SOURCE			SYSCLK_SRC_OSC0
#define CONFIG_SYSCLK_SOURCE			SYSCLK_SRC_DFLL
//#define CONFIG_SYSCLK_SOURCE			SYSCLK_SRC_RC120M
//#define CONFIG_SYSCLK_SOURCE			SYSCLK_SRC_PLL0

/* Fbus = Fsys / (2 ^ BUS_div) */
#define CONFIG_SYSCLK_CPU_DIV			0
#define CONFIG_SYSCLK_PBA_DIV			0
#define CONFIG_SYSCLK_PBB_DIV			0

//#define CONFIG_USBCLK_SOURCE			USBCLK_SRC_OSC0
//#define CONFIG_USBCLK_SOURCE			USBCLK_SRC_PLL0

/* Fusb = Fsys / USB_div */
//#define CONFIG_USBCLK_DIV				1

//#define CONFIG_PLL0_SOURCE			PLL_SRC_OSC0

/* Fpll0 = (Fclk * PLL_mul) / PLL_div */
//#define CONFIG_PLL0_MUL				(48000000UL / BOARD_OSC32_HZ)
//#define CONFIG_PLL0_DIV				1

//#define CONFIG_DFLL0_SOURCE			GENCLK_SRC_OSC0
#define CONFIG_DFLL0_SOURCE				GENCLK_SRC_RCSYS
//#define CONFIG_DFLL0_SOURCE			GENCLK_SRC_OSC32K
//#define CONFIG_DFLL0_SOURCE			GENCLK_SRC_RC120M
//#define CONFIG_DFLL0_SOURCE			GENCLK_SRC_RC32K

/* Fdfll = (Fclk * DFLL_mul) / DFLL_div */
#define CONFIG_DFLL0_MUL				(417)
#define CONFIG_DFLL0_DIV				1

#define F_CPU 48000000UL

#endif /* CONF_CLOCK_H_INCLUDED */
