#ifndef CONF_DRIVERS_H_
#define CONF_DRIVERS_H_

// MCU Clock config
#define CONF_CPU_F 		48000000UL
#define CONF_PBA_F		48000000UL
#define CONF_PBB_F		48000000UL
#define CONF_DFLL_F		48000000UL

// USART
#define CONF_USART_POINTER 	(&AVR32_USART0)
#define CONF_USART_BAUDRATE	9600
#define CONF_USART_CHARLENGTH	8
#define CONF_USART_PARITYPE	USART_NO_PARITY
#define CONF_USART_STOPBITS	USART_2_STOPBITS
#define CONF_USART_CHANNELMODE USART_NORMAL_CHMODE

// GPI// 0 O
#define CONF_GPIO_PA00_FUNCTION	AVR32_USART0_TXD_0_FUNCTION
#define CONF_USART0_TXD			AVR32_PIN_PA00
#define CONF_GPIO_PA01_FUNCTION	AVR32_USART0_RXD_0_FUNCTION
#define CONF_USART0_RXD			AVR32_PIN_PA01

#endif /* CONF_DRIVERS_H_ */